name: Python CI

on:
  push:
    branches: [ "task_oop" ]
  pull_request:
    branches: [ "task_oop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10.16"

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        sudo apt-get update
        sudo apt-get install -y python3-tk xvfb

    - name: Run main.py with virtual display
      run: |
        xvfb-run -a python main.py
